#!/bin/bash
# Helper script to guide test user creation
# This script provides instructions for creating test users

echo "📋 Test User Setup Instructions"
echo ""
echo "To create test users for Grace Community Church demo:"
echo ""
echo "1. Go to Supabase Dashboard: https://supabase.com/dashboard/project/qauwthppncedppwvctfh"
echo "2. Navigate to: Authentication → Users → Add User"
echo ""
echo "Create these 4 users:"
echo ""
echo "   User 1:"
echo "   - Email: admin@gracechurch.org"
echo "   - Password: admin123"
echo ""
echo "   User 2:"
echo "   - Email: member@gracechurch.org"
echo "   - Password: member123"
echo ""
echo "   User 3:"
echo "   - Email: moderator@gracechurch.org"
echo "   - Password: moderator123"
echo ""
echo "   User 4:"
echo "   - Email: finance@gracechurch.org"
echo "   - Password: finance123"
echo ""
echo "3. After creating users, run this SQL query in Supabase SQL Editor:"
echo ""
echo "   First, get user IDs:"
echo "   SELECT id, email FROM auth.users WHERE email IN ("
echo "     'admin@gracechurch.org',"
echo "     'member@gracechurch.org',"
echo "     'moderator@gracechurch.org',"
echo "     'finance@gracechurch.org'"
echo "   );"
echo ""
echo "4. Then update scripts/create-test-users.sql with the actual user IDs"
echo "5. Run scripts/create-test-users.sql in SQL Editor"
echo ""
echo "Alternatively, you can manually insert memberships:"
echo "   INSERT INTO org_memberships (org_id, user_id, role)"
echo "   VALUES "
echo "     ('11111111-1111-1111-1111-111111111111', '<admin-user-id>', 'admin'),"
echo "     ('11111111-1111-1111-1111-111111111111', '<member-user-id>', 'member'),"
echo "     ('11111111-1111-1111-1111-111111111111', '<moderator-user-id>', 'moderator'),"
echo "     ('11111111-1111-1111-1111-111111111111', '<finance-user-id>', 'finance');"
echo ""
